account/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView
from .views import LoginView, RegistrationView

app_name = 'account'

urlpatterns = [
    path('logout/', LogoutView.as_view(), name='logout'),
    path('login/', LoginView.as_view(), name='login'),
    path('signup/', RegistrationView.as_view(), name='signup'),
]

blog/urls.py
from django.urls import path

from .views import *
app_name = 'blog'
urlpatterns = [
    path('blog/', BlogListView.as_view(), name='blog_list'),
    path('blog/<slug>', BlogDetailsView.as_view(), name='blog_details'),
]

page/urls.py
from django.urls import path
from .views import *

app_name = 'page'
urlpatterns = [
    path('', IndexView.as_view(), name='index')
]

product/urls.py
from django.urls import path

from .views import ProductListView, ProductDetailView

app_name = 'product'
urlpatterns = [
    path('product/', ProductListView.as_view(), name='product_list'),
    path('product/<slug>/', ProductDetailView.as_view(), name='product_detail'),
]

templates/base/footer.html
<footer id="footer" class="dark"> {% load front_tags %}

			<div id="copyrights">

				<div class="container clearfix">
                    {% front_edit "footer_container" request.path request.LANGUAGE_CODE %}

					<div class="col_half">
						Copyrights &copy; 2017-2019 All Rights Reserved by Pollexe Co.<br>
						<div class="copyright-links"><a href="#">Terms of Use</a> / <a href="#">Privacy Policy</a></div>
					</div>

					<div class="col_half col_last tright">
						<div class="fright clearfix">
							<a href="#" class="social-icon si-small si-borderless si-facebook">
								<i class="icon-facebook"></i>
								<i class="icon-facebook"></i>
							</a>

							<a href="#" class="social-icon si-small si-borderless si-twitter">
								<i class="icon-twitter"></i>
								<i class="icon-twitter"></i>
							</a>

							<a href="#" class="social-icon si-small si-borderless si-gplus">
								<i class="icon-gplus"></i>
								<i class="icon-gplus"></i>
							</a>

							<a href="#" class="social-icon si-small si-borderless si-pinterest">
								<i class="icon-pinterest"></i>
								<i class="icon-pinterest"></i>
							</a>

							<a href="#" class="social-icon si-small si-borderless si-vimeo">
								<i class="icon-vimeo"></i>
								<i class="icon-vimeo"></i>
							</a>

							<a href="#" class="social-icon si-small si-borderless si-github">
								<i class="icon-github"></i>
								<i class="icon-github"></i>
							</a>

							<a href="#" class="social-icon si-small si-borderless si-yahoo">
								<i class="icon-yahoo"></i>
								<i class="icon-yahoo"></i>
							</a>

							<a href="#" class="social-icon si-small si-borderless si-linkedin">
								<i class="icon-linkedin"></i>
								<i class="icon-linkedin"></i>
							</a>
						</div>

						<div class="clear"></div>

						<i class="icon-envelope2"></i> info@pollexe.com <span class="middot">&middot;</span> <i class="icon-headphones"></i> +8801742353078 <span class="middot">&middot;</span>
					</div>
                    {% end_front_edit  %}
				</div>

			</div><!-- #copyrights end -->

		</footer>

templates/base/header.html
{% load static %}
{% url 'page:index' as index_url %}
{% url 'blog:blog_list' as blog_list_url %}
{% url 'product:product_list' as product_list %}
<header id="header" class="full-header dark">
    <div id="header-wrap">
        <div class="container clearfix">

            <div id="primary-menu-trigger"><i class="icon-reorder"></i></div>

            <!-- Logo
            ============================================= -->
            <div id="logo">
                <!--<a href="{{ index_url }}" class="standard-logo" data-dark-logo="{% static 'images/logo-dark.png' %}"><img src="images/logo.png" alt="Canvas Logo"></a>-->
                <!--<a href="{{ index_url }}" class="retina-logo" data-dark-logo="{% static 'images/logo-dark@2x.png' %}"><img src="images/logo@2x.png" alt="Canvas Logo"></a>-->
                <a href="{{ index_url }}" class="standard-logo" data-dark-logo="">POLLEXE Co.</a>
                <!--<a href="{{ index_url }}" class="retina-logo" data-dark-logo="">POLLEXE Co.</a>-->
            </div>

            <!-- Primary Navigation
            ============================================= -->
            <nav id="primary-menu">

                <ul>
                    <li><a href="{{ index_url }}">Home</a></li>
                    <li><a href="{{ product_list }}">Product</a></li>
                    <li><a href="{{ blog_list_url }}">Blog</a></li>
                    <li><a href="#">Contact</a></li>
                </ul>

                <!-- Top Cart
                ============================================= -->
                <div id="top-cart">
                    <a href="#" id="top-cart-trigger"><i class="icon-users"></i></a>
                    <div class="top-cart-content">
                        <div class="top-cart-items">
                            <div class="top-cart-item clearfix">
                                {% if request.user.is_authenticated %}
                                <div class="top-cart-item-desc">
                                    <a href="#"><i class="icon-dashboard mr-2"></i> Dashboard</a>
                                </div>
                                <div class="top-cart-item-desc mt-3">
                                    <a href="{% url 'account:logout' %}"><i class="icon-line2-logout mr-2"></i> Logout</a>
                                </div>
                                {% else %}
                                <div class="top-cart-item-desc">
                                    <a href="{% url 'account:login' %}"><i class="icon-dashboard mr-2"></i>  Login</a>
                                </div>
                                <div class="top-cart-item-desc mt-2">
                                    <a href="{% url 'account:signup' %}"><i class="icon-dashboard mr-2"></i>  Registration</a>
                                </div>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                </div><!-- #top-cart end -->

                <!-- Top Search
                ============================================= -->
                <div id="top-search">
                    <a href="#" id="top-search-trigger"><i class="icon-search3"></i><i class="icon-line-cross"></i></a>
                    <form action="search.html" method="get">
                        <input type="text" name="q" class="form-control" value="" placeholder="Type &amp; Hit Enter..">
                    </form>
                </div><!-- #top-search end -->

            </nav><!-- #primary-menu end -->

        </div>

    </div>
</header>